// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// A resilient auth lock. The default navigator.locks-based lock in @supabase/auth-js
// can wait indefinitely when the lock is held by another tab or a crashed/stale
// session, which freezes signInWithPassword forever (button stuck, no error).
// This version caps how long it will wait for the lock, then proceeds anyway so
// authentication can never hang permanently.
async function resilientLock<R>(name: string, acquireTimeout: number, fn: () => Promise<R>): Promise<R> {
  const nav = typeof globalThis !== 'undefined' ? (globalThis as any).navigator : undefined;
  if (!nav?.locks?.request) {
    return await fn();
  }
  const controller = new AbortController();
  const waitMs = acquireTimeout > 0 ? acquireTimeout : 5000;
  const timer = setTimeout(() => controller.abort(), waitMs);
  try {
    return await nav.locks.request(
      name,
      { mode: 'exclusive', signal: controller.signal },
      async () => {
        clearTimeout(timer);
        return await fn();
      },
    );
  } catch {
    // Lock was contended/stale and could not be acquired in time — run without it.
    clearTimeout(timer);
    return await fn();
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    lock: resilientLock,
  }
});
